# Generated by Django 6.0 on 2025-12-31 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_enquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firm_name',
            field=models.CharField(blank=True, help_text='For Owners: Legal Firm Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='linked_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
