# Generated by Django 6.0 on 2025-12-27 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='For Owners: Business, Student, Startup, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
