# Generated by Django 6.0 on 2026-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='Email for sending client notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Gmail App Password', max_length=100, null=True),
        ),
    ]
